name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install -g grunt-cli
    - run: npm install
    - run: grunt
